---
cluster.name: "hot-warm-cluster"
node.name: "master-node"

node.master: true
node.data: false
node.ingest: false
cluster.remote.connect: false

network.host: master-node
http.port: 9200
transport.port: 9300

cluster.initial_master_nodes: ["master-node"]
discovery.seed_hosts: ["master-node:9300", "hot-node-1:9301", "hot-node-2:9302", "warm-node-1:9303", "warm-node-2:9304"]